// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGUkt4SFoTNkFdmc7V7L_9BAhiV-gQY44',
    appId: '1:155028662700:web:b49a487c84224fc1b37209',
    messagingSenderId: '155028662700',
    projectId: 'strixtok',
    authDomain: 'strixtok.firebaseapp.com',
    storageBucket: 'strixtok.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPzmbZlWbjoIlS1Hr2CRmw0z_stfPYCpU',
    appId: '1:155028662700:android:e712ee87e283ddbfb37209',
    messagingSenderId: '155028662700',
    projectId: 'strixtok',
    storageBucket: 'strixtok.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz6CAmLN0D-JHoG8HA7ejsxWr3Iw4V3Bs',
    appId: '1:155028662700:ios:4cc14ce4179d7573b37209',
    messagingSenderId: '155028662700',
    projectId: 'strixtok',
    storageBucket: 'strixtok.appspot.com',
    iosBundleId: 'com.jianyang.tiktokHackers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz6CAmLN0D-JHoG8HA7ejsxWr3Iw4V3Bs',
    appId: '1:155028662700:ios:683768507a5c0236b37209',
    messagingSenderId: '155028662700',
    projectId: 'strixtok',
    storageBucket: 'strixtok.appspot.com',
    iosBundleId: 'com.example.tiktokHackers.RunnerTests',
  );
}
